accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', signup_page, name='signup'),
    path('accounts/login/', login_page, name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('', home, name='home'),
    path('dashboard/question-set/', question_set, name='question_set'),
    path('dashboard/question-set/view/', questions_set_list, name='question_set_view'),
    path('dashboard/add_question/', add_question, name='add_question'),
    path('dashboard/question_list/', question_list, name='question_list'),

    path('dashboard/add_question_options/', add_question_options, name='add_question_options'),
    path('dashboard/question_option_list/', question_option_list, name='question_option_list'),

    path('dashboard/exam_detail_page/<int:id>/<slug:slug>/', exam_detail_page, name='exam_detail_page'),


    path('dashboard/users/', users_list, name='users'),

]

mobihive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from accounts.managers import UserManager
from django.utils.text import slugify

# Create your models here.

# User Role Table.
class Role(models.Model):
    Admin = 1
    User = 2
    ROLE_CHOICES = [
        (Admin, 'Admin'),
        (User, 'User'),
    ]
    role = models.CharField(
        max_length=10,
        default='User',
        null=False
    )

    class Meta:
        db_table = "user_roles"

    def __str__(self):
        return self.role



### User Model
class User(AbstractBaseUser):
    email = models.EmailField(unique=True, max_length=255)
    name = models.CharField(max_length=255, null=True, blank=True)
    roles = models.ForeignKey(Role, on_delete=models.CASCADE, null=True,blank=True)
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'  # this now over rides the username field and now email is the default field
    # REQUIRED_FIELDS = [] if you add another field and need it to be required, include it in the list

    objects = UserManager()

    class Meta:
        db_table = 'users'
        ordering = ('-timestamp', )
        indexes = [
            models.Index(fields=['name','email',]),
        ]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    """@property
    def is_active(self):
        return self.is_active"""

## Question Set Model Here.

class QuestionSet(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, blank=True, null=True)
    enable_negative_marking = models.BooleanField(default=False)
    negative_marking_percentage = models.IntegerField(blank=True, null=True)
    ideal_timeto_complete = models.IntegerField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'questions_set'
        ordering = ('-created_on', )
        indexes = [
            models.Index(fields=['name','slug',]),
        ]
    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

### Question Model Here.
class Question(models.Model):
    question_set = models.ForeignKey(QuestionSet, on_delete=models.CASCADE,blank=True, null=True)
    text = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to ='question/', null=True, blank=True)
    QUEST_CHOICES = [
        ('Radio', 'Radio'),
        ('CheckBox', 'CheckBox'),
        ('Matrix', 'Matrix'),
    ]
    type = models.CharField(max_length=15,choices=QUEST_CHOICES,default='Radio',null=False)
    order = models.IntegerField(blank=True,null=True)
    marks = models.IntegerField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.text

    class Meta:
        db_table = 'questions'
        ordering = ('-created_on', )
        indexes = [
            models.Index(fields=['question_set',]),
        ]

### Question Options Model Here.
class QuestionOptions(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,blank=True, null=True)
    text = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to ='question/options/', null=True, blank=True)
    order = models.IntegerField(blank=True,null=True)
    marks = models.IntegerField(blank=True, null=True)
    answer = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'question_options'
        ordering = ('-created_on', )
        indexes = [
            models.Index(fields=['question',]),
        ]

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from accounts.models import Question, QuestionOptions, QuestionSet

User = get_user_model()



### Login Form.
class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control form-control-lg',
                                                                           'placeholder': 'Enter email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg',
                                                                                   'placeholder': 'Enter password'}))

### Register Form.
class RegistrationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Confirm password'}))
    name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Name'}))

    class Meta:
        model = User
        fields = ['name','email',]
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Email'})}

    def clean_password2(self):  # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.is_active = True
            user.roles_id = 2
            user.save()
        return user

### Question Set Form.
class QuestionSetForm(forms.ModelForm):
    name = forms.CharField(label='Question Set Name')
    negative_marking_percentage = forms.IntegerField(label='Negative Marking Percentage', required=False)
    ideal_timeto_complete = forms.IntegerField(label='Ideal Timeto Complete')

    STATUS_CHOICES =(
    (False, False),
    (True, True),
    )

    enable_negative_marking = forms.ChoiceField(choices = STATUS_CHOICES)
    
    class Meta:
        model = QuestionSet
        fields = ['name','enable_negative_marking','negative_marking_percentage', 'ideal_timeto_complete']
    def __init__(self, *args, **kwargs):
        super(QuestionSetForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'
    

#### Questions Form #####
class QuestionForm(forms.ModelForm):
    text = forms.CharField(label='Question Name', required=False)
    marks = forms.IntegerField(label='Question Mark')
    order = forms.IntegerField(label='Question Order')
    class Meta:
        model = Question
        fields = ['question_set','text','image','marks','order','type']
    
    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

        self.fields['question_set'].required = True

#### Add Questions Options Form ####

class QuestionOptionsForm(forms.ModelForm):
    order = forms.IntegerField(label='Order')
    STATUS_CHOICES =(
    (False, False),
    (True, True),
    )

    answer = forms.ChoiceField(label='Answer',choices = STATUS_CHOICES)
    class Meta:
        model = QuestionOptions
        fields = ['question','text','image','order','answer']

    def __init__(self, *args, **kwargs):
        super(QuestionOptionsForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

        self.fields['question'].required = True

 
        

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from accounts.decorators import unauthenticated_user

from accounts.forms import *
from django.utils import timezone

from accounts.models import QuestionSet
from accounts.serialziers import QuestionSetSerializer
User = get_user_model()




### signup_page
@unauthenticated_user
def signup_page(request):
    form = RegistrationForm()
    
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You have registered successfully. Please login here.')
            return redirect(settings.LOGIN_URL)
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
            form = RegistrationForm(request.POST)

            
    context = {'title': 'Register', 'form':form}
    return render(request, 'accounts/register.html', context)
    

### Login Page.
@unauthenticated_user
def login_page(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            now = timezone.now()
            user = authenticate(request, username=email, password=password)
            if user is not None:
                # print('user', user)
                login(request, user)
               
                return redirect(settings.LOGIN_REDIRECT_URL)  # change expected_url in your project
            else:
                messages.error(request, 'Incorrect email or password')
        elif form.errors:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

    context = {'title': 'Login','form':form}
    return render(request, 'accounts/login.html', context)


## logout_view
def logout_view(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)

### Dashboard Page
@login_required
def home(request):
    user_count = User.objects.filter(roles_id=2).count()
    qs_set = QuestionSet.objects.count()
    question_count = Question.objects.count()
    qs_option = QuestionOptions.objects.count()

    question_set_list = QuestionSet.objects.all()
    context = {'title': 'Admin','user_count':user_count,'qs_set':qs_set,'question_count':question_count,'qs_option':qs_option,'question_set_list':question_set_list}
    return render(request, 'accounts/dashboard/index.html', context)


## Question Set Views.
@login_required
def question_set(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)
        
        
    form = QuestionSetForm()
    if request.method == 'POST':
        form = QuestionSetForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Record has been added successfully.')
            return redirect('/dashboard/question-set/')

        elif form.errors:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

    context = {'title': 'Question Set','form':form}
    return render(request, 'accounts/questionset/index.html', context)

@login_required
def questions_set_list(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    question_set = QuestionSet.objects.all()
    print('question_set', question_set)
    context = {'title': 'Question Set List','question_set':question_set}
    return render(request, 'accounts/questionset/view.html', context)

@login_required
def add_question(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    form = QuestionForm()
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)

        # print('form', form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Question has been added successfully.')
            return redirect('/dashboard/add_question/')

        elif form.errors:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

    context = {'title': 'Add New Questions','form':form}
    return render(request, 'accounts/questions/index.html', context)

@login_required
def question_list(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    question = Question.objects.all()
    print('question', question)
    context = {'title': 'Question List','question':question}
    return render(request, 'accounts/questions/view.html', context)

#### Add Question Options #####.
@login_required
def add_question_options(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    form = QuestionOptionsForm()
    if request.method == 'POST':
        form = QuestionOptionsForm(request.POST, request.FILES)

        # print('form', form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Question option has been added successfully.')
            return redirect('/dashboard/add_question_options/')

        elif form.errors:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

    context = {'title': 'Add New Questions Option','form':form}
    return render(request, 'accounts/question_options/add.html', context)

@login_required
def question_option_list(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    options_list = QuestionOptions.objects.all()
    context = {'title': 'Question Option List','options_list':options_list}
    return render(request, 'accounts/question_options/view.html', context)


### Exam Detail Page SHow All Question List Options.
@login_required
def exam_detail_page(request, id, slug):
    if request.method == 'POST':
        return redirect('/')
        

    question_set_check = QuestionSet.objects.filter(id=id, slug=slug).last()
    if question_set_check:
        serializer = QuestionSetSerializer(question_set_check, many=False)

        print('>>>>>>>>>', serializer.data)
        context = {'title': 'Exam Detail Page','data':serializer.data}
        return render(request, 'accounts/exam/index.html', context)
    else:
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)
    
### User Management Start Here.
@login_required
def users_list(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)
        
    users = User.objects.filter(roles_id=2)
    context = {'title': 'Users List','users':users}
    return render(request, 'accounts/users/index.html', context)



    
    

templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Login</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/base/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/mobihive.png' %}" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                
                <img src="{% static 'images/mobihive.png' %}" alt="logo" style="background: #248afd;padding: 10px;">
              </div>
              <h4>Hello! let's get started</h4>
              <h6 class="font-weight-light">Sign in to continue.</h6>
              {% include 'accounts/messages.html' %}
                <form method="POST" id="signup-form" class="pt-3">
                  {% csrf_token %}
                  {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
                {% endfor %}
                <div class="mt-3">
                  <input type="submit" name="submit" id="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" value="SIGN IN"/>
                  
                </div>
                <div class="my-2 d-flex justify-content-between align-items-center">
                  <div class="form-check">
                    <label class="form-check-label text-muted">
                      <input type="checkbox" class="form-check-input">
                      Keep me signed in
                    </label>
                  </div>
                 
                </div>
                
                <div class="text-center mt-4 font-weight-light">
                  Don't have an account? <a href="{% url 'accounts:signup' %}" class="text-primary">Create</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'vendors/base/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'js/template.js' %}"></script>
  <script src="{% static 'js/todolist.js' %}"></script>
  <!-- endinject -->
</body>

</html>

templates/accounts/messages.html
<div class="col-md-12">
    {% if messages %}
      {% for message in messages %}
         {% if message.tags == 'success' %}
            <div class="alert alert-success alert-with-icon">
              <span data-notify="icon" class="tim-icons icon-bell-55"></span>
              <span data-notify="message">{{ message }}</span>
            </div>
         {% else %}
            <div class="alert alert-warning alert-with-icon">
              <span data-notify="icon" class="tim-icons icon-alert-circle-exc"></span>
              <span data-notify="message">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    {% endif %}
  </div>

templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Register</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/base/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/mobihive.png' %}" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="{% static 'images/mobihive.png' %}" alt="logo">
              </div>
              <h4>New here?</h4>
              <h6 class="font-weight-light">Signing up is easy. It only takes a few steps</h6>
              {% include 'accounts/messages.html' %}
              <form method="POST" id="signup-form" class="pt-3">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
                {% endfor %}

               
               
                
                <div class="mb-4">
                  <div class="form-check">
                    <label class="form-check-label text-muted">
                      <input type="checkbox" class="form-check-input">
                      I agree to all Terms & Conditions
                    </label>
                  </div>
                </div>
                <div class="mt-3">
                  <input type="submit" name="submit" id="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" value="SIGN UP"/>
                 
                </div>
                <div class="text-center mt-4 font-weight-light">
                  Already have an account? <a href="{% url 'accounts:login' %}" class="text-primary">Login</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'vendors/base/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="{% static 'js/off-canvas.js' %}"></script>
  <script src="{% static 'js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'js/template.js' %}"></script>
  <script src="{% static 'js/todolist.js' %}"></script>
  <!-- endinject -->
</body>

</html>