accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', signup_page, name='signup'),
    path('accounts/login/', login_page, name='login'),
    path('accounts/logout/', logout_view, name='logout'),
    path('', home, name='home'),
    path('dashboard/question-set/', question_set, name='question_set'),
    path('dashboard/question-set/view/', questions_set_list, name='question_set_view'),
    path('dashboard/add_question/', add_question, name='add_question'),
    path('dashboard/question_list/', question_list, name='question_list'),

    path('dashboard/add_question_options/', add_question_options, name='add_question_options'),
    path('dashboard/question_option_list/', question_option_list, name='question_option_list'),

    path('dashboard/exam_detail_page/<int:id>/<slug:slug>/', exam_detail_page, name='exam_detail_page'),


    path('dashboard/users/', users_list, name='users'),

]

mobihive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from accounts.managers import UserManager
from django.utils.text import slugify

# Create your models here.

# User Role Table.
class Role(models.Model):
    Admin = 1
    User = 2
    ROLE_CHOICES = [
        (Admin, 'Admin'),
        (User, 'User'),
    ]
    role = models.CharField(
        max_length=10,
        default='User',
        null=False
    )

    class Meta:
        db_table = "user_roles"

    def __str__(self):
        return self.role



### User Model
class User(AbstractBaseUser):
    email = models.EmailField(unique=True, max_length=255)
    name = models.CharField(max_length=255, null=True, blank=True)
    roles = models.ForeignKey(Role, on_delete=models.CASCADE, null=True,blank=True)
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'  # this now over rides the username field and now email is the default field
    # REQUIRED_FIELDS = [] if you add another field and need it to be required, include it in the list

    objects = UserManager()

    class Meta:
        db_table = 'users'
        ordering = ('-timestamp', )
        indexes = [
            models.Index(fields=['name','email',]),
        ]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    """@property
    def is_active(self):
        return self.is_active"""

## Question Set Model Here.

class QuestionSet(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, blank=True, null=True)
    enable_negative_marking = models.BooleanField(default=False)
    negative_marking_percentage = models.IntegerField(blank=True, null=True)
    ideal_timeto_complete = models.IntegerField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'questions_set'
        ordering = ('-created_on', )
        indexes = [
            models.Index(fields=['name','slug',]),
        ]
    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

### Question Model Here.
class Question(models.Model):
    question_set = models.ForeignKey(QuestionSet, on_delete=models.CASCADE,blank=True, null=True)
    text = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to ='question/', null=True, blank=True)
    QUEST_CHOICES = [
        ('Radio', 'Radio'),
        ('CheckBox', 'CheckBox'),
        ('Matrix', 'Matrix'),
    ]
    type = models.CharField(max_length=15,choices=QUEST_CHOICES,default='Radio',null=False)
    order = models.IntegerField(blank=True,null=True)
    marks = models.IntegerField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.text

    class Meta:
        db_table = 'questions'
        ordering = ('-created_on', )
        indexes = [
            models.Index(fields=['question_set',]),
        ]

### Question Options Model Here.
class QuestionOptions(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,blank=True, null=True)
    text = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to ='question/options/', null=True, blank=True)
    order = models.IntegerField(blank=True,null=True)
    marks = models.IntegerField(blank=True, null=True)
    answer = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'question_options'
        ordering = ('-created_on', )
        indexes = [
            models.Index(fields=['question',]),
        ]

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from accounts.models import Question, QuestionOptions, QuestionSet

User = get_user_model()



### Login Form.
class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control form-control-lg',
                                                                           'placeholder': 'Enter email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg',
                                                                                   'placeholder': 'Enter password'}))

### Register Form.
class RegistrationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Confirm password'}))
    name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Name'}))

    class Meta:
        model = User
        fields = ['name','email',]
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter Email'})}

    def clean_password2(self):  # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.is_active = True
            user.roles_id = 2
            user.save()
        return user

### Question Set Form.
class QuestionSetForm(forms.ModelForm):
    name = forms.CharField(label='Question Set Name')
    negative_marking_percentage = forms.IntegerField(label='Negative Marking Percentage', required=False)
    ideal_timeto_complete = forms.IntegerField(label='Ideal Timeto Complete')

    STATUS_CHOICES =(
    (False, False),
    (True, True),
    )

    enable_negative_marking = forms.ChoiceField(choices = STATUS_CHOICES)
    
    class Meta:
        model = QuestionSet
        fields = ['name','enable_negative_marking','negative_marking_percentage', 'ideal_timeto_complete']
    def __init__(self, *args, **kwargs):
        super(QuestionSetForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'
    

#### Questions Form #####
class QuestionForm(forms.ModelForm):
    text = forms.CharField(label='Question Name', required=False)
    marks = forms.IntegerField(label='Question Mark')
    order = forms.IntegerField(label='Question Order')
    class Meta:
        model = Question
        fields = ['question_set','text','image','marks','order','type']
    
    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

        self.fields['question_set'].required = True

#### Add Questions Options Form ####

class QuestionOptionsForm(forms.ModelForm):
    order = forms.IntegerField(label='Order')
    STATUS_CHOICES =(
    (False, False),
    (True, True),
    )

    answer = forms.ChoiceField(label='Answer',choices = STATUS_CHOICES)
    class Meta:
        model = QuestionOptions
        fields = ['question','text','image','order','answer']

    def __init__(self, *args, **kwargs):
        super(QuestionOptionsForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

        self.fields['question'].required = True

 
        

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from accounts.decorators import unauthenticated_user

from accounts.forms import *
from django.utils import timezone

from accounts.models import QuestionSet
from accounts.serialziers import QuestionSetSerializer
User = get_user_model()




### signup_page
@unauthenticated_user
def signup_page(request):
    form = RegistrationForm()
    
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You have registered successfully. Please login here.')
            return redirect(settings.LOGIN_URL)
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
            form = RegistrationForm(request.POST)

            
    context = {'title': 'Register', 'form':form}
    return render(request, 'accounts/register.html', context)
    

### Login Page.
@unauthenticated_user
def login_page(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            now = timezone.now()
            user = authenticate(request, username=email, password=password)
            if user is not None:
                # print('user', user)
                login(request, user)
               
                return redirect(settings.LOGIN_REDIRECT_URL)  # change expected_url in your project
            else:
                messages.error(request, 'Incorrect email or password')
        elif form.errors:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

    context = {'title': 'Login','form':form}
    return render(request, 'accounts/login.html', context)


## logout_view
def logout_view(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)

### Dashboard Page
@login_required
def home(request):
    user_count = User.objects.filter(roles_id=2).count()
    qs_set = QuestionSet.objects.count()
    question_count = Question.objects.count()
    qs_option = QuestionOptions.objects.count()

    question_set_list = QuestionSet.objects.all()
    context = {'title': 'Admin','user_count':user_count,'qs_set':qs_set,'question_count':question_count,'qs_option':qs_option,'question_set_list':question_set_list}
    return render(request, 'accounts/dashboard/index.html', context)


## Question Set Views.
@login_required
def question_set(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)
        
        
    form = QuestionSetForm()
    if request.method == 'POST':
        form = QuestionSetForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Record has been added successfully.')
            return redirect('/dashboard/question-set/')

        elif form.errors:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

    context = {'title': 'Question Set','form':form}
    return render(request, 'accounts/questionset/index.html', context)

@login_required
def questions_set_list(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    question_set = QuestionSet.objects.all()
    print('question_set', question_set)
    context = {'title': 'Question Set List','question_set':question_set}
    return render(request, 'accounts/questionset/view.html', context)

@login_required
def add_question(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    form = QuestionForm()
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)

        # print('form', form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Question has been added successfully.')
            return redirect('/dashboard/add_question/')

        elif form.errors:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

    context = {'title': 'Add New Questions','form':form}
    return render(request, 'accounts/questions/index.html', context)

@login_required
def question_list(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    question = Question.objects.all()
    print('question', question)
    context = {'title': 'Question List','question':question}
    return render(request, 'accounts/questions/view.html', context)

#### Add Question Options #####.
@login_required
def add_question_options(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    form = QuestionOptionsForm()
    if request.method == 'POST':
        form = QuestionOptionsForm(request.POST, request.FILES)

        # print('form', form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Question option has been added successfully.')
            return redirect('/dashboard/add_question_options/')

        elif form.errors:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

    context = {'title': 'Add New Questions Option','form':form}
    return render(request, 'accounts/question_options/add.html', context)

@login_required
def question_option_list(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

    options_list = QuestionOptions.objects.all()
    context = {'title': 'Question Option List','options_list':options_list}
    return render(request, 'accounts/question_options/view.html', context)


### Exam Detail Page SHow All Question List Options.
@login_required
def exam_detail_page(request, id, slug):
    if request.method == 'POST':
        return redirect('/')
        

    question_set_check = QuestionSet.objects.filter(id=id, slug=slug).last()
    if question_set_check:
        serializer = QuestionSetSerializer(question_set_check, many=False)

        print('>>>>>>>>>', serializer.data)
        context = {'title': 'Exam Detail Page','data':serializer.data}
        return render(request, 'accounts/exam/index.html', context)
    else:
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)
    
### User Management Start Here.
@login_required
def users_list(request):
    if request.user.roles.role != 'Admin':
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)
        
    users = User.objects.filter(roles_id=2)
    context = {'title': 'Users List','users':users}
    return render(request, 'accounts/users/index.html', context)



    
    

templates/accounts/dashboard/footer.html
{% load static %}
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © <a href="#" target="_blank">Mobihive Labs </a>2023</span>
      
    </div>
  </footer>
  <!-- partial -->
</div>
<!-- main-panel ends -->
</div>
<!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->

<!-- plugins:js -->
<script src="{% static 'vendors/base/vendor.bundle.base.js' %}"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript"></script>
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{% static 'js/off-canvas.js' %}"></script>
<script src="{% static 'js/hoverable-collapse.js' %}"></script>
<script src="{% static 'js/template.js' %}"></script>
<script src="{% static 'js/todolist.js' %}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{% static 'js/dashboard.js' %}"></script>
<!-- End custom js for this page-->
</body>

</html>

templates/accounts/dashboard/header.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{{title}}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/base/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'images/mobihive.png' %}" />
</head>
<body>
  
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo me-5" href="index.html"><img src="{% static 'images/mobihive.png' %}" class="me-2" alt="logo"/></a>
        <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{% static 'images/mobihive.png' %}" alt="logo"/></a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="ti-view-list"></span>
        </button>
        
        <ul class="navbar-nav navbar-nav-right">
        
         
          <li class="nav-item nav-profile dropdown">
            <b>Hi, {{request.user.name}}</b>
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="profileDropdown">
              <img src="{% static 'images/mobihive.png' %}" alt="profile"/>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
             
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                <i class="ti-power-off text-primary"></i>
                Logout
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="ti-view-list"></span>
        </button>
      </div>
    </nav>

templates/accounts/dashboard/index.html
{% include "accounts/dashboard/header.html" %}
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
      {% comment %} Sidebar {% endcomment %}
      {% include "accounts/dashboard/sidebar.html" with active_tab='dashboard_tab' %}
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-md-12 grid-margin">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h4 class="font-weight-bold mb-0">Attend Exam Dashboard</h4>
                </div>
               
              </div>
            </div>
          </div>
          <div class="row">
           

         {% if request.user.roles_id == 1 %}
         <div class="col-md-3 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <p class="card-title text-md-center text-xl-left">Users</p>
              <div class="d-flex flex-wrap justify-content-between justify-content-md-center justify-content-xl-between align-items-center">
                <h3 class="mb-0 mb-md-2 mb-xl-0 order-md-1 order-xl-0">{{user_count}}</h3>
                <i class="ti-calendar icon-md text-muted mb-0 mb-md-3 mb-xl-0"></i>
              </div>  
             
            </div>
          </div>
        </div>

         <div class="col-md-3 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <p class="card-title text-md-center text-xl-left">QuestionSet</p>
              <div class="d-flex flex-wrap justify-content-between justify-content-md-center justify-content-xl-between align-items-center">
                <h3 class="mb-0 mb-md-2 mb-xl-0 order-md-1 order-xl-0">{{qs_set}}</h3>
                <i class="ti-user icon-md text-muted mb-0 mb-md-3 mb-xl-0"></i>
              </div>  
              
            </div>
          </div>
        </div>

        <div class="col-md-3 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <p class="card-title text-md-center text-xl-left">Questions</p>
              <div class="d-flex flex-wrap justify-content-between justify-content-md-center justify-content-xl-between align-items-center">
                <h3 class="mb-0 mb-md-2 mb-xl-0 order-md-1 order-xl-0">{{question_count}}</h3>
                <i class="ti-agenda icon-md text-muted mb-0 mb-md-3 mb-xl-0"></i>
              </div>  
              
            </div>
          </div>
        </div>

        <div class="col-md-3 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <p class="card-title text-md-center text-xl-left">Question Option</p>
              <div class="d-flex flex-wrap justify-content-between justify-content-md-center justify-content-xl-between align-items-center">
                <h3 class="mb-0 mb-md-2 mb-xl-0 order-md-1 order-xl-0">{{qs_option}}</h3>
                <i class="ti-layers-alt icon-md text-muted mb-0 mb-md-3 mb-xl-0"></i>
              </div>  
              
            </div>
          </div>
        </div>
        {% else %}

        {% if question_set_list %}

        {% for row in question_set_list %}

        <div class="col-md-3 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <p class="card-title text-md-center text-xl-left" style="text-align: inherit!important;">Question Set : {{row.name}}</p>
              <div class="d-flex flex-wrap justify-content-between justify-content-md-center justify-content-xl-between align-items-center">
                
                <h4 class="mb-0 mb-md-2 mb-xl-0 order-md-1 order-xl-0">Total Times : {{row.ideal_timeto_complete}} minutes</h4>
                <a href="{% url 'accounts:exam_detail_page' row.id row.slug %}" class="btn btn-info" style="margin-top: 18px;box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;"> Start Exam</a>
              </div>  
              
            </div>
          </div>
        </div>
        {% endfor %}
        {% endif %}

         {% endif %}


          </div>


         
          
          
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        {% include "accounts/dashboard/footer.html" %}

templates/accounts/dashboard/sidebar.html
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      <li class="nav-item {% if active_tab == 'dashboard_tab' %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:home' %}">
          <i class="ti-shield menu-icon"></i>
          <span class="menu-title">Dashboard</span>

          
        </a>
      </li>
     
     

      {% if request.user.roles_id == 1 %}
      <li class="nav-item {% if active_tab == 'questionset_tab' %}active{% endif %}"> 
        <a class="nav-link" href="{% url 'accounts:question_set' %}">
          <i class="ti-layout-list-post menu-icon"></i>
          <span class="menu-title">Add New QuestionSet</span>
        </a>
      </li>
      <li class="nav-item {% if active_tab == 'questionset_view_tab' %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:question_set_view' %}">
          <i class="ti-layout-list-post menu-icon"></i>
          <span class="menu-title">QuestionSet List</span>
        </a>
      </li>
      <li class="nav-item {% if active_tab == 'question_add_tab' %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:add_question' %}">
          <i class="ti-pie-chart menu-icon"></i>
          <span class="menu-title">Add New Question</span>
        </a>
      </li>

      <li class="nav-item {% if active_tab == 'question_list' %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:question_list' %}">
          <i class="ti-pie-chart menu-icon"></i>
          <span class="menu-title">Question List</span>
        </a>
      </li>

      <li class="nav-item {% if active_tab == 'add_question_options' %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:add_question_options' %}">
          <i class="ti-pie-chart menu-icon"></i>
          <span class="menu-title">Add New Question Options</span>
        </a>
      </li>

      <li class="nav-item {% if active_tab == 'question_option_list' %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:question_option_list' %}">
          <i class="ti-pie-chart menu-icon"></i>
          <span class="menu-title">Question Options List</span>
        </a>
      </li>

      

      <li class="nav-item {% if active_tab == 'users_view_tab' %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:users' %}">
          <i class="ti-view-list-alt menu-icon"></i>
          <span class="menu-title">User<span>
        </a>
      </li>
      {% endif %}
     
     
     
    </ul>
  </nav>